// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kknuzsmjttjaabxomnyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrbnV6c21qdHRqYWFieG9tbnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzI2ODcsImV4cCI6MjA2NDEwODY4N30.pxX-TZe_B8ThodlitCYFoJZYnk1kyAKB6zea1JyuEac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);